export enum Resource {
  USERS = 'users',
  Roles = 'roles',
  TEAMS = 'teams',
  BANNERS = 'banners',
  SETTINGS = 'settings',
  SECTIONS = 'sections',
  SERVICES = 'services',
  TESTIMONIALS = 'testimonials',
  CONTACT = 'contact',
  NEWS = 'news',
  SUBSCRIBE = 'subscribe',
  PARTNERS = 'partners',
  JUDGMENTS = 'judgments',
  CATEGORIES = 'categories',
  SUB_CATEGORIES = 'sub-categories',
  PRODUCTS = 'products',
}