/** Convert a 2-letter ISO 3166-1 alpha-2 code to its flag emoji */
export const toFlagEmoji = (code: string): string =>
  code.toUpperCase().replace(/./g, (c) =>
    String.fromCodePoint(c.charCodeAt(0) + 127397)
  );

export type Country = { name: string; ar: string; code: string };

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", ar: "أفغانستان", code: "AF" },
  { name: "Albania", ar: "ألبانيا", code: "AL" },
  { name: "Algeria", ar: "الجزائر", code: "DZ" },
  { name: "Andorra", ar: "أندورا", code: "AD" },
  { name: "Angola", ar: "أنغولا", code: "AO" },
  { name: "Antigua and Barbuda", ar: "أنتيغوا وبربودا", code: "AG" },
  { name: "Argentina", ar: "الأرجنتين", code: "AR" },
  { name: "Armenia", ar: "أرمينيا", code: "AM" },
  { name: "Australia", ar: "أستراليا", code: "AU" },
  { name: "Austria", ar: "النمسا", code: "AT" },
  { name: "Azerbaijan", ar: "أذربيجان", code: "AZ" },
  { name: "Bahamas", ar: "جزر البهاما", code: "BS" },
  { name: "Bahrain", ar: "البحرين", code: "BH" },
  { name: "Bangladesh", ar: "بنغلاديش", code: "BD" },
  { name: "Barbados", ar: "بربادوس", code: "BB" },
  { name: "Belarus", ar: "بيلاروسيا", code: "BY" },
  { name: "Belgium", ar: "بلجيكا", code: "BE" },
  { name: "Belize", ar: "بليز", code: "BZ" },
  { name: "Benin", ar: "بنين", code: "BJ" },
  { name: "Bhutan", ar: "بوتان", code: "BT" },
  { name: "Bolivia", ar: "بوليفيا", code: "BO" },
  { name: "Bosnia and Herzegovina", ar: "البوسنة والهرسك", code: "BA" },
  { name: "Botswana", ar: "بوتسوانا", code: "BW" },
  { name: "Brazil", ar: "البرازيل", code: "BR" },
  { name: "Brunei", ar: "بروناي", code: "BN" },
  { name: "Bulgaria", ar: "بلغاريا", code: "BG" },
  { name: "Burkina Faso", ar: "بوركينا فاسو", code: "BF" },
  { name: "Burundi", ar: "بوروندي", code: "BI" },
  { name: "Cabo Verde", ar: "الرأس الأخضر", code: "CV" },
  { name: "Cambodia", ar: "كمبوديا", code: "KH" },
  { name: "Cameroon", ar: "الكاميرون", code: "CM" },
  { name: "Canada", ar: "كندا", code: "CA" },
  { name: "Central African Republic", ar: "جمهورية أفريقيا الوسطى", code: "CF" },
  { name: "Chad", ar: "تشاد", code: "TD" },
  { name: "Chile", ar: "تشيلي", code: "CL" },
  { name: "China", ar: "الصين", code: "CN" },
  { name: "Colombia", ar: "كولومبيا", code: "CO" },
  { name: "Comoros", ar: "جزر القمر", code: "KM" },
  { name: "Congo (Congo-Brazzaville)", ar: "الكونغو", code: "CG" },
  { name: "Costa Rica", ar: "كوستاريكا", code: "CR" },
  { name: "Croatia", ar: "كرواتيا", code: "HR" },
  { name: "Cuba", ar: "كوبا", code: "CU" },
  { name: "Cyprus", ar: "قبرص", code: "CY" },
  { name: "Czechia", ar: "التشيك", code: "CZ" },
  { name: "Denmark", ar: "الدنمارك", code: "DK" },
  { name: "Djibouti", ar: "جيبوتي", code: "DJ" },
  { name: "Dominica", ar: "دومينيكا", code: "DM" },
  { name: "Dominican Republic", ar: "جمهورية الدومينيكان", code: "DO" },
  { name: "Ecuador", ar: "الإكوادور", code: "EC" },
  { name: "Egypt", ar: "مصر", code: "EG" },
  { name: "El Salvador", ar: "السلفادور", code: "SV" },
  { name: "Equatorial Guinea", ar: "غينيا الاستوائية", code: "GQ" },
  { name: "Eritrea", ar: "إريتريا", code: "ER" },
  { name: "Estonia", ar: "إستونيا", code: "EE" },
  { name: "Eswatini", ar: "إسواتيني", code: "SZ" },
  { name: "Ethiopia", ar: "إثيوبيا", code: "ET" },
  { name: "Fiji", ar: "فيجي", code: "FJ" },
  { name: "Finland", ar: "فنلندا", code: "FI" },
  { name: "France", ar: "فرنسا", code: "FR" },
  { name: "Gabon", ar: "الغابون", code: "GA" },
  { name: "Gambia", ar: "غامبيا", code: "GM" },
  { name: "Georgia", ar: "جورجيا", code: "GE" },
  { name: "Germany", ar: "ألمانيا", code: "DE" },
  { name: "Ghana", ar: "غانا", code: "GH" },
  { name: "Greece", ar: "اليونان", code: "GR" },
  { name: "Grenada", ar: "غرينادا", code: "GD" },
  { name: "Guatemala", ar: "غواتيمالا", code: "GT" },
  { name: "Guinea", ar: "غينيا", code: "GN" },
  { name: "Guinea-Bissau", ar: "غينيا بيساو", code: "GW" },
  { name: "Guyana", ar: "غيانا", code: "GY" },
  { name: "Haiti", ar: "هايتي", code: "HT" },
  { name: "Honduras", ar: "هندوراس", code: "HN" },
  { name: "Hungary", ar: "المجر", code: "HU" },
  { name: "Iceland", ar: "آيسلندا", code: "IS" },
  { name: "India", ar: "الهند", code: "IN" },
  { name: "Indonesia", ar: "إندونيسيا", code: "ID" },
  { name: "Iran", ar: "إيران", code: "IR" },
  { name: "Iraq", ar: "العراق", code: "IQ" },
  { name: "Ireland", ar: "أيرلندا", code: "IE" },
  { name: "Israel", ar: "إسرائيل", code: "IL" },
  { name: "Italy", ar: "إيطاليا", code: "IT" },
  { name: "Jamaica", ar: "جامايكا", code: "JM" },
  { name: "Japan", ar: "اليابان", code: "JP" },
  { name: "Jordan", ar: "الأردن", code: "JO" },
  { name: "Kazakhstan", ar: "كازاخستان", code: "KZ" },
  { name: "Kenya", ar: "كينيا", code: "KE" },
  { name: "Kiribati", ar: "كيريباتي", code: "KI" },
  { name: "Kuwait", ar: "الكويت", code: "KW" },
  { name: "Kyrgyzstan", ar: "قيرغيزستان", code: "KG" },
  { name: "Laos", ar: "لاوس", code: "LA" },
  { name: "Latvia", ar: "لاتفيا", code: "LV" },
  { name: "Lebanon", ar: "لبنان", code: "LB" },
  { name: "Lesotho", ar: "ليسوتو", code: "LS" },
  { name: "Liberia", ar: "ليبيريا", code: "LR" },
  { name: "Libya", ar: "ليبيا", code: "LY" },
  { name: "Liechtenstein", ar: "ليختنشتاين", code: "LI" },
  { name: "Lithuania", ar: "ليتوانيا", code: "LT" },
  { name: "Luxembourg", ar: "لوكسمبورغ", code: "LU" },
  { name: "Madagascar", ar: "مدغشقر", code: "MG" },
  { name: "Malawi", ar: "مالاوي", code: "MW" },
  { name: "Malaysia", ar: "ماليزيا", code: "MY" },
  { name: "Maldives", ar: "جزر المالديف", code: "MV" },
  { name: "Mali", ar: "مالي", code: "ML" },
  { name: "Malta", ar: "مالطا", code: "MT" },
  { name: "Marshall Islands", ar: "جزر مارشال", code: "MH" },
  { name: "Mauritania", ar: "موريتانيا", code: "MR" },
  { name: "Mauritius", ar: "موريشيوس", code: "MU" },
  { name: "Mexico", ar: "المكسيك", code: "MX" },
  { name: "Micronesia", ar: "ميكرونيزيا", code: "FM" },
  { name: "Moldova", ar: "مولدوفا", code: "MD" },
  { name: "Monaco", ar: "موناكو", code: "MC" },
  { name: "Mongolia", ar: "منغوليا", code: "MN" },
  { name: "Montenegro", ar: "الجبل الأسود", code: "ME" },
  { name: "Morocco", ar: "المغرب", code: "MA" },
  { name: "Mozambique", ar: "موزمبيق", code: "MZ" },
  { name: "Myanmar", ar: "ميانمار", code: "MM" },
  { name: "Namibia", ar: "ناميبيا", code: "NA" },
  { name: "Nauru", ar: "ناورو", code: "NR" },
  { name: "Nepal", ar: "نيبال", code: "NP" },
  { name: "Netherlands", ar: "هولندا", code: "NL" },
  { name: "New Zealand", ar: "نيوزيلندا", code: "NZ" },
  { name: "Nicaragua", ar: "نيكاراغوا", code: "NI" },
  { name: "Niger", ar: "النيجر", code: "NE" },
  { name: "Nigeria", ar: "نيجيريا", code: "NG" },
  { name: "North Korea", ar: "كوريا الشمالية", code: "KP" },
  { name: "North Macedonia", ar: "مقدونيا الشمالية", code: "MK" },
  { name: "Norway", ar: "النرويج", code: "NO" },
  { name: "Oman", ar: "عُمان", code: "OM" },
  { name: "Pakistan", ar: "باكستان", code: "PK" },
  { name: "Palau", ar: "بالاو", code: "PW" },
  { name: "Palestine State", ar: "فلسطين", code: "PS" },
  { name: "Panama", ar: "بنما", code: "PA" },
  { name: "Papua New Guinea", ar: "بابوا غينيا الجديدة", code: "PG" },
  { name: "Paraguay", ar: "باراغواي", code: "PY" },
  { name: "Peru", ar: "بيرو", code: "PE" },
  { name: "Philippines", ar: "الفلبين", code: "PH" },
  { name: "Poland", ar: "بولندا", code: "PL" },
  { name: "Portugal", ar: "البرتغال", code: "PT" },
  { name: "Qatar", ar: "قطر", code: "QA" },
  { name: "Romania", ar: "رومانيا", code: "RO" },
  { name: "Russia", ar: "روسيا", code: "RU" },
  { name: "Rwanda", ar: "رواندا", code: "RW" },
  { name: "Saint Kitts and Nevis", ar: "سانت كيتس ونيفيس", code: "KN" },
  { name: "Saint Lucia", ar: "سانت لوسيا", code: "LC" },
  { name: "Saint Vincent and the Grenadines", ar: "سانت فنسنت وجزر غرينادين", code: "VC" },
  { name: "Samoa", ar: "ساموا", code: "WS" },
  { name: "San Marino", ar: "سان مارينو", code: "SM" },
  { name: "Sao Tome and Principe", ar: "ساو تومي وبرينسيبي", code: "ST" },
  { name: "Saudi Arabia", ar: "المملكة العربية السعودية", code: "SA" },
  { name: "Senegal", ar: "السنغال", code: "SN" },
  { name: "Serbia", ar: "صربيا", code: "RS" },
  { name: "Seychelles", ar: "سيشل", code: "SC" },
  { name: "Sierra Leone", ar: "سيراليون", code: "SL" },
  { name: "Singapore", ar: "سنغافورة", code: "SG" },
  { name: "Slovakia", ar: "سلوفاكيا", code: "SK" },
  { name: "Slovenia", ar: "سلوفينيا", code: "SI" },
  { name: "Solomon Islands", ar: "جزر سليمان", code: "SB" },
  { name: "Somalia", ar: "الصومال", code: "SO" },
  { name: "South Africa", ar: "جنوب أفريقيا", code: "ZA" },
  { name: "South Korea", ar: "كوريا الجنوبية", code: "KR" },
  { name: "South Sudan", ar: "جنوب السودان", code: "SS" },
  { name: "Spain", ar: "إسبانيا", code: "ES" },
  { name: "Sri Lanka", ar: "سريلانكا", code: "LK" },
  { name: "Sudan", ar: "السودان", code: "SD" },
  { name: "Suriname", ar: "سورينام", code: "SR" },
  { name: "Sweden", ar: "السويد", code: "SE" },
  { name: "Switzerland", ar: "سويسرا", code: "CH" },
  { name: "Syria", ar: "سوريا", code: "SY" },
  { name: "Tajikistan", ar: "طاجيكستان", code: "TJ" },
  { name: "Tanzania", ar: "تنزانيا", code: "TZ" },
  { name: "Thailand", ar: "تايلاند", code: "TH" },
  { name: "Timor-Leste", ar: "تيمور الشرقية", code: "TL" },
  { name: "Togo", ar: "توغو", code: "TG" },
  { name: "Tonga", ar: "تونغا", code: "TO" },
  { name: "Trinidad and Tobago", ar: "ترينيداد وتوباغو", code: "TT" },
  { name: "Tunisia", ar: "تونس", code: "TN" },
  { name: "Turkey", ar: "تركيا", code: "TR" },
  { name: "Turkmenistan", ar: "تركمانستان", code: "TM" },
  { name: "Tuvalu", ar: "توفالو", code: "TV" },
  { name: "Uganda", ar: "أوغندا", code: "UG" },
  { name: "Ukraine", ar: "أوكرانيا", code: "UA" },
  { name: "United Arab Emirates", ar: "الإمارات العربية المتحدة", code: "AE" },
  { name: "United Kingdom", ar: "المملكة المتحدة", code: "GB" },
  { name: "United States", ar: "الولايات المتحدة", code: "US" },
  { name: "Uruguay", ar: "أوروغواي", code: "UY" },
  { name: "Uzbekistan", ar: "أوزبكستان", code: "UZ" },
  { name: "Vanuatu", ar: "فانواتو", code: "VU" },
  { name: "Venezuela", ar: "فنزويلا", code: "VE" },
  { name: "Vietnam", ar: "فيتنام", code: "VN" },
  { name: "Yemen", ar: "اليمن", code: "YE" },
  { name: "Zambia", ar: "زامبيا", code: "ZM" },
  { name: "Zimbabwe", ar: "زيمبابوي", code: "ZW" },
];

export const PRACTICE_SUBSCRIPTIONS = [
  "Banking & Finance",
  "Capital Markets",
  "Competition & Antitrust",
  "Construction & Infrastructure",
  "Corporate & Commercial",
  "Data Protection & Privacy",
  "Dispute Resolution & Litigation",
  "Employment & Labour",
  "Energy & Natural Resources",
  "Environmental Law",
  "Family & Personal",
  "Intellectual Property",
  "Arbitration",
  "Real Estate",
  "Restructuring & Insolvency",
  "Tax",
  "Technology & Telecommunications",
];

export const SECTOR_SUBSCRIPTIONS = [
  "Aviation & Aerospace",
  "Banking & Financial Services",
  "Construction & Real Estate",
  "Education",
  "Energy & Natural Resources",
  "Government & Public Sector",
  "Healthcare & Life Sciences",
  "Hospitality & Leisure",
  "Insurance",
  "Manufacturing & Industrial",
  "Media & Entertainment",
  "Retail & Consumer",
  "Technology & Telecommunications",
  "Transport & Logistics",
];
